name: openapi_repository
description: A starting point for Dart libraries or applications.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  openapi_repository_annotations:
    path: '../openapi_repository_annotations'
    # git: 
    #   url: "https://github.com/ajilo297/list_bloc.git"
    #   path: packages/openapi_repository_annotations
  build: ^2.3.0
  built_collection: ^5.1.1
  built_value: ^8.3.2
  dio: ^4.0.6
  mustache_template: ^2.0.0
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
