name: flutter_list_bloc
description: A Flutter package to display the data loaded with list_bloc.
version: 4.0.0
homepage: https://github.com/apexlabs-ai/list_bloc/

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter_bloc: ^8.0.1
  list_bloc: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # list_bloc:
  #   path: ../list_bloc

flutter:
